### ISSUE TITLE
Migrate to Polymer 3

### ISSUE THREAD

**Issue by yveslange** [advanced-rest-client/paper-chip#1]
Hi, 

would you mind migrating to Polymer 3 ?

https://polymer-library.polymer-project.org/3.0/docs/upgrade

That would be kind

Best regards

**Comment by jarrodek** [comment]
Hi,
Sorry for late response. 2 weeks ago I have migrated the component to LitELement. Basically you won't see any difference. One braking change is that `removeIcon` property is mapped to `removeicon` attribute (instead of `remove-icon`).
